version: '3.8'

services:
  pg-db:
    container_name: space-traders-db
    image: postgres:bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: space-traders
    volumes:
      - space-traders-db:/var/lib/postgresql/data
    networks:
      - space-traders-network

volumes:
  space-traders-db:

networks:
  space-traders-network:
    name: space-traders-network
